# Generated by Django 4.2.7 on 2024-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
