# Generated by Django 4.2.7 on 2024-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resume_mobile_alter_resume_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
